//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Страховая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avto
    {
        public string GosNum { get; set; }
        public string Categ { get; set; }
        public string Marka_avto { get; set; }
        public string Model { get; set; }
        public int God_avto { get; set; }
        public string Power { get; set; }
        public string VIN { get; set; }
        public string PTS { get; set; }
        public System.DateTime Data_Vidachi { get; set; }
        public int Passport_vlad { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
