//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Страховая
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAskorNewEntities : DbContext
    {
        private static DbAskorNewEntities _context;
        public DbAskorNewEntities()
            : base("name=DbAskorNewEntities")
        {
        }
        public static DbAskorNewEntities GetContext()
        {
            if (_context == null)
                _context = new DbAskorNewEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Strahov> Strahov { get; set; }
    }
}
