//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Страховая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Avto
    {
        public string F { get; set; }
        public string I { get; set; }
        public string O { get; set; }
        public System.DateTime DR { get; set; }
        public double Passport { get; set; }
        public string Gosnum { get; set; }
        public string Categ { get; set; }
        public string Marka_avto { get; set; }
        public string Model { get; set; }
        public int God_avto { get; set; }
        public int Power { get; set; }
        public string VIN { get; set; }
        public string PTS { get; set; }
        public System.DateTime Data_Vidachi { get; set; }
    }
}
