//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Страховая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Passport { get; set; }
        public string F { get; set; }
        public string I { get; set; }
        public string O { get; set; }
        public System.DateTime DR { get; set; }
    
        public virtual Avto Avto { get; set; }
    }
}
