//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Страховая
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAskorEntities : DbContext
    {
        private static DbAskorEntities _context;
        public DbAskorEntities()
            : base("name=DbAskorEntities")
        {
        }
        public static DbAskorEntities GetContext()
        {
            if (_context == null)
                _context = new DbAskorEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DBAvto> DBAvto { get; set; }
        public virtual DbSet<DBClient> DBClient { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
