//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Страховая
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AskorOneEntities1 : DbContext
    {
        private static AskorOneEntities1 _context;
        public AskorOneEntities1()
            : base("name=AskorOneEntities1")
        {
        }
        public static AskorOneEntities1 GetContext()
        {
            if (_context == null)
                _context = new AskorOneEntities1();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client_Avto> Client_Avto { get; set; }
    }
}
